export const HomeTextMock = {
  firstSection: `<p>Amazônia perdeu 12% da sua superfície de água - um total de asdasdsads1.104.575 ha - nos últimos 30 anos, anunciou em setembro do asdasdsadsano passado um levantamento da rede colaborativa MabBiomas. O cenário de deterioração de rios e demais corpos aquáticos é o mesmo em outros biomas brasileiros. Segundo a iniciativa, “a dinâmica de uso da terra baseada na conversão da floresta para pecuária e agricultura e a construção de represas contribuem para a diminuição do fluxo hídrico”. </p> 
  <p>Esse número negativo impressionante expõe de modo trágico a crise hídrica brasileira e exige uma revisão em debates, estudos e políticas de conservação do meio ambiente. </p>
  <p>Na mixórdia de elementos naturais que constituem a identidade ecológica da Amazônia, a terra historicamente se sobressai. Cobiçado por colonizadores desde o século 16, o solo da floresta tropical vem sofrendo uma exploração de seus recursos com impactos severos – hoje sabemos, de escala global, no fogo que consome as árvores e libera no ar o carbono acumulado, ajudando a impulsionar as mudanças no clima. </p>
  <p>Tal processo tem sido o eixo central em discussões que mobilizam cientistas, ambientalistas e legisladores engajados na preservação da região selvagem mais biodiversa do planeta. </p>
  <p>Mais do que nunca, contudo, é urgente olhar para o outro elemento da natureza. </p>
  <p>Na Amazônia, a água é o agente de conexão. Ela transborda do degelo dos Andes e escorre na forma de rios que, ao longo de seu curso, alimentam comunidades humanas e irrigam matas e planícies ricas em espécies da fauna e flora. A evapotranspiração da biomassa vegetal produz novas águas em um ciclo anual de chuvas que retroalimentam os estoques do bioma e viajam Brasil afora - os chamados “rios voadores” irão irrigar lavouras e garantir o abastecimento de centros urbanos mais ao sul. </p>
  <p>A Bacia Hidrográfica Amazônica cobre uma área de 7 milhões de quilômetros quadrados ao longo de oito países, concentra 20% da água doce líquida superficial do planeta e responde por aproximadamente 18% de toda a água doce que chega aos oceanos. </p>
  <p>Clima, economia, ciência, cultura, ecologia, energia, política, biodiversidade: isto é a floresta-água.</p> `,
  secondSection: `<p>Índice de Impacto nas Águas na Amazônia não pretende ser uma asasaaasa ferramenta de precisão acadêmica, mas um produto de jornalismo asasaaasa científico com base em dados disponíveis. Seu objetivo é expor as zonas de impacto com clareza gráfica, ao lado de opiniões qualificadas. E, com isso, tornar-se uma plataforma de referência para o entendimento dos principais impactos da atividade humana nos ecossistemas aquáticos da Bacia Amazônica.</p>
  <p>No debate internacional sobre a conservação da região, predomina há décadas o padrão de levantamento e análise de dados sobre a degradação da cobertura vegetal: as queimadas, o desmatamento, os garimpeiros, o boi, a soja. A Amazônia como fonte de matérias-primas. Os ecossistemas aquáticos também sofrem com todas as mazelas da intensa atividade humana - a perda da floresta afeta o ciclo hidrológico -, mas os danos são mais difíceis de serem identificados e entendidos, seja em monitoramento remoto, seja em dados de pesquisa científica. </p>
  `,
  thirdSection: `<p>Um corpo hídrico não sofre apenas com a poluição causada pelos resíduos urbanos, como normalmente pensamos. “Quando falamos de fogo, de degradação florestal, não se trata apenas do ar ou do solo: isso também significa problemas no ambiente aquático”, diz Cecília Gontijo Leal, bióloga da Escola Superior de Agricultura Luiz de Queiroz e integrante da Rede Amazônia Sustentável (RAS). “Existe uma certa simplificação nas pesquisas. Ao aferir o impacto de uma obra que afeta um rio, muitas vezes se lida apenas com os problemas da vegetação das margens.”</p>
  <p>“Mesmo que a maioria dos impactos aferidos no índice esteja acontecendo na terra, o nosso olhar voltou-se para a localização, a intensidade e a escala da pressão que exercem sobre os corpos hídricos, em cada microbacia”, explica Cecília, consultora científica do projeto Aquazônia.</p>
  <p>Muitas vezes, foi preciso flexibilizar as medidas dos impactos, seja pela ausência de dados seja pelo fato de que cada microbacia é um complexo ecológico individual, pleno de particularidades ambientais ou legais. Por exemplo: a degradação causada por barragens de hidrelétricas e desmatamento é mais clara. O mesmo não se pode dizer das redes de milhares de pequenas estradas clandestinas que cortam a floresta. Mais: dados de pesca e de agrotóxicos, importantes para definir melhor os parâmetros de qualidade da água, são inconsistentes em uma escala espacial tão grande quanto a da bacia.</p>
  <p>“Na Amazônia, os impactos mudam de acordo com a característica de cada ecossistema”, diz Cecília. “O desmatamento afeta mais as matas de igapó perto da cabeceira dos rios. Já um barramento de igarapé altera a dinâmica do ambiente, seu fluxo de matéria orgânica, de sedimentos. Contudo, os efeitos de longo prazo são ainda desconhecidos.”</p>
  <p>Igualmente desafiador foi aferir o alvo, o alcance e a força de cada fator de pressão. Os impactos são piores para as populações locais ou para a fauna e flora? Difícil precisar - eles nem sequer são efetivos para todos os animais. Peixes migradores, por exemplo, sofrem com os barramentos da água para estradas e usinas, mas outras espécies não sentem. No caso das hidrelétricas, foi definido um padrão: 30 km de alcance do impacto para usinas com mais de 1 000 MW de capacidade instalada, e 10 km para usinas menores.</p>
  <p>Não é possível também saber o alcance exato dos danos que a mineração clandestina deixa na água - o mercúrio usado para separar metais contamina as águas e destrói cadeias tróficas. Neste e em outros casos, impactos em terras indígenas e unidades de conservação tiveram peso maior, pois a falta de fiscalização e a presença de atividades ilegais impedem que tais reservas exerçam seu papel constitucional.</p>
  <p>Por fim, se não é ainda possível mensurar qual atividade específica gera maior impacto nas águas, “é certo que eles são maiores nas regiões em que as atividades se sobrepõem”, diz Leandro Castello, pesquisador da Universidade Virginia Tech que estuda a pressão da sobrepesca – e seus riscos na economia e na segurança alimentar – na Amazônia.</p>
  <p>“O que conseguimos dizer é que as áreas mais degradadas são aquelas em que as pressões se somam. Quando ampliamos um zoom nas microbacias, fica claro que o impacto na água é tão forte quanto na terra”, completa Laura Kurtzberg, professora na Universidade Internacional da Flórida e especialista em visualização de dados. “É um drama silencioso.”</p>
  <p>E, a tudo isso, soma-se o impacto menos tangível das mudanças climáticas. O resultado final do índice traz uma visão geral concreta das ameaças à bacia, mas limites devem ser compreendidos.</p>
  `,
  forthSection: `<p>asasaaasa Índice de Impacto nas Águas na Amazônia não pretende ser uma asasaaasa ferramenta de precisão acadêmica, mas um produto de jornalismo asasaaasa científico com base em dados disponíveis. Seu objetivo é expor as zonas de impacto com clareza gráfica, ao lado de opiniões qualificadas. E, com isso, tornar-se uma plataforma de referência para o entendimento dos principais impactos da atividade humana nos ecossistemas aquáticos da Bacia Amazônica.</p>
  <p>No debate internacional sobre a conservação da região, predomina há décadas o padrão de levantamento e análise de dados sobre a degradação da cobertura vegetal: as queimadas, o desmatamento, os garimpeiros, o boi, a soja. A Amazônia como fonte de matérias-primas. Os ecossistemas aquáticos também sofrem com todas as mazelas da intensa atividade humana - a perda da floresta afeta o ciclo hidrológico -, mas os danos são mais difíceis de serem identificados e entendidos, seja em monitoramento remoto, seja em dados de pesquisa científica. </p>
  `
}
